import Link from "next/link";
import { Zen_Old_Mincho, Zen_Tokyo_Zoo } from "next/font/google";

const fontTokyo = Zen_Old_Mincho({
  subsets: ["latin"],
  display: "swap",
  weight: "700",
});

export const metadata = {
  title: "wild-oasis",
  description: "Generated by Next.js",
};
console.log(fontTokyo);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontTokyo.className}`}>
        <Link href="/cabins">Cabins</Link>
        <div>{children}</div>
      </body>
    </html>
  );
}
