import Link from "next/link";

export const metadata = {
  title: "wild-oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/cabins">Cabins</Link>
        <div>{children}</div>
      </body>
    </html>
  );
}
